# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: fadeltd.XiaomiDebloater
PackageVersion: 1.1.0
InstallerType: portable
Commands:
- xiaomi-debloater
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Google.PlatformTools
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/fadeltd/xiaomi-debloater/releases/download/v1.1.0/xiaomi-debloater-v1.1.0-windows-amd64.exe
  InstallerSha256: 405B87E88437073200CF14123ED13C065E7A5C969622F4F79EDEE57AF734FA75
- Architecture: arm64
  InstallerUrl: https://github.com/fadeltd/xiaomi-debloater/releases/download/v1.1.0/xiaomi-debloater-v1.1.0-windows-arm64.exe
  InstallerSha256: 8D3AD9447BF90D31F2AE91293CE6A0155287215C22DBFE24BEDCB8D73EB52D3A
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2026-09-27
